// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClicksByURL = `-- name: CountClicksByURL :one
SELECT COUNT(*) AS total
FROM url_clicks
WHERE url_id = $1
`

func (q *Queries) CountClicksByURL(ctx context.Context, urlID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksByURL, urlID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countClicksPerIP = `-- name: CountClicksPerIP :many
SELECT ip, COUNT(*) AS total
FROM url_clicks
WHERE url_id = $1
GROUP BY ip
ORDER BY total DESC
LIMIT $2
`

type CountClicksPerIPParams struct {
	UrlID int64 `json:"url_id"`
	Limit int32 `json:"limit"`
}

type CountClicksPerIPRow struct {
	Ip    *netip.Addr `json:"ip"`
	Total int64       `json:"total"`
}

func (q *Queries) CountClicksPerIP(ctx context.Context, arg CountClicksPerIPParams) ([]*CountClicksPerIPRow, error) {
	rows, err := q.db.Query(ctx, countClicksPerIP, arg.UrlID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CountClicksPerIPRow
	for rows.Next() {
		var i CountClicksPerIPRow
		if err := rows.Scan(&i.Ip, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClick = `-- name: CreateClick :one
INSERT INTO url_clicks (url_id, ip, user_agent, referer)
VALUES ($1, $2, $3, $4)
RETURNING id, url_id, created_at, ip, user_agent, referer, country
`

type CreateClickParams struct {
	UrlID     int64       `json:"url_id"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent *string     `json:"user_agent"`
	Referer   *string     `json:"referer"`
}

func (q *Queries) CreateClick(ctx context.Context, arg CreateClickParams) (*UrlClick, error) {
	row := q.db.QueryRow(ctx, createClick,
		arg.UrlID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
	)
	var i UrlClick
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Country,
	)
	return &i, err
}

const deleteClicksBefore = `-- name: DeleteClicksBefore :exec
DELETE FROM url_clicks
WHERE created_at < $1
`

func (q *Queries) DeleteClicksBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteClicksBefore, createdAt)
	return err
}

const getClicksByURL = `-- name: GetClicksByURL :many
SELECT id, ip, user_agent, referer, created_at
FROM url_clicks
WHERE url_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetClicksByURLParams struct {
	UrlID  int64 `json:"url_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetClicksByURLRow struct {
	ID        int64              `json:"id"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent *string            `json:"user_agent"`
	Referer   *string            `json:"referer"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetClicksByURL(ctx context.Context, arg GetClicksByURLParams) ([]*GetClicksByURLRow, error) {
	rows, err := q.db.Query(ctx, getClicksByURL, arg.UrlID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetClicksByURLRow
	for rows.Next() {
		var i GetClicksByURLRow
		if err := rows.Scan(
			&i.ID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
