// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordReset struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TwofaBackupCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Url struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	LongUrl     string             `json:"long_url"`
	LongUrlHash []byte             `json:"long_url_hash"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	IsActive    bool               `json:"is_active"`
	IsPrivate   bool               `json:"is_private"`
	Clicks      int64              `json:"clicks"`
}

type UrlClick struct {
	ID        int64              `json:"id"`
	UrlID     int64              `json:"url_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent *string            `json:"user_agent"`
	Referer   *string            `json:"referer"`
	Country   *string            `json:"country"`
	IpHash    []byte             `json:"ip_hash"`
	Device    *string            `json:"device"`
	Os        *string            `json:"os"`
	Browser   *string            `json:"browser"`
	IsBot     *bool              `json:"is_bot"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaSecret     *string            `json:"twofa_secret"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
