// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountClicksByURL(ctx context.Context, urlID int64) (int64, error)
	CountClicksPerIP(ctx context.Context, arg CountClicksPerIPParams) ([]*CountClicksPerIPRow, error)
	CreateClick(ctx context.Context, arg CreateClickParams) (*UrlClick, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (*Url, error)
	DeactivateURL(ctx context.Context, id int64) error
	DeleteClicksBefore(ctx context.Context, createdAt pgtype.Timestamptz) error
	GetActiveURLByCode(ctx context.Context, code string) (*GetActiveURLByCodeRow, error)
	GetAndIncrementURL(ctx context.Context, code string) (*GetAndIncrementURLRow, error)
	GetClicksByURL(ctx context.Context, arg GetClicksByURLParams) ([]*GetClicksByURLRow, error)
	GetCodeByHash(ctx context.Context, longUrlHash []byte) (string, error)
	GetLongURLByHash(ctx context.Context, longUrlHash []byte) (string, error)
	GetURLByCode(ctx context.Context, code string) (*GetURLByCodeRow, error)
	GetURLByID(ctx context.Context, id int64) (*Url, error)
	GetURLsByUser(ctx context.Context, userID pgtype.UUID) ([]*GetURLsByUserRow, error)
	IncrementClicks(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
