// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (code, long_url, long_url_hash, user_id, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, long_url, long_url_hash, user_id, created_at, expires_at, is_active, is_private, clicks
`

type CreateURLParams struct {
	Code        string             `json:"code"`
	LongUrl     string             `json:"long_url"`
	LongUrlHash []byte             `json:"long_url_hash"`
	UserID      pgtype.UUID        `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (*Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.Code,
		arg.LongUrl,
		arg.LongUrlHash,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.LongUrlHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.IsPrivate,
		&i.Clicks,
	)
	return &i, err
}

const deactivateURL = `-- name: DeactivateURL :exec
UPDATE urls
SET is_active = false
WHERE id = $1
`

func (q *Queries) DeactivateURL(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateURL, id)
	return err
}

const getActiveURLByCode = `-- name: GetActiveURLByCode :one
SELECT id, long_url
FROM urls
WHERE code = $1
  AND is_active = true
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

type GetActiveURLByCodeRow struct {
	ID      int64  `json:"id"`
	LongUrl string `json:"long_url"`
}

func (q *Queries) GetActiveURLByCode(ctx context.Context, code string) (*GetActiveURLByCodeRow, error) {
	row := q.db.QueryRow(ctx, getActiveURLByCode, code)
	var i GetActiveURLByCodeRow
	err := row.Scan(&i.ID, &i.LongUrl)
	return &i, err
}

const getAndIncrementURL = `-- name: GetAndIncrementURL :one
UPDATE urls
SET clicks = clicks + 1
WHERE code = $1
  AND is_active = true
  AND (expires_at IS NULL OR expires_at > NOW())
RETURNING id, long_url, long_url_hash
`

type GetAndIncrementURLRow struct {
	ID          int64  `json:"id"`
	LongUrl     string `json:"long_url"`
	LongUrlHash []byte `json:"long_url_hash"`
}

func (q *Queries) GetAndIncrementURL(ctx context.Context, code string) (*GetAndIncrementURLRow, error) {
	row := q.db.QueryRow(ctx, getAndIncrementURL, code)
	var i GetAndIncrementURLRow
	err := row.Scan(&i.ID, &i.LongUrl, &i.LongUrlHash)
	return &i, err
}

const getCodeByHash = `-- name: GetCodeByHash :one
SELECT code
FROM urls
WHERE long_url_hash = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetCodeByHash(ctx context.Context, longUrlHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getCodeByHash, longUrlHash)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getLongURLByHash = `-- name: GetLongURLByHash :one
SELECT long_url
FROM urls
WHERE long_url_hash = $1
  AND is_active = TRUE
  AND (expires_at IS NULL OR expires_at > NOW())
LIMIT 1
`

func (q *Queries) GetLongURLByHash(ctx context.Context, longUrlHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getLongURLByHash, longUrlHash)
	var long_url string
	err := row.Scan(&long_url)
	return long_url, err
}

const getURLByCode = `-- name: GetURLByCode :one
SELECT id, long_url, is_active, expires_at
FROM urls
WHERE code = $1
LIMIT 1
`

type GetURLByCodeRow struct {
	ID        int64              `json:"id"`
	LongUrl   string             `json:"long_url"`
	IsActive  bool               `json:"is_active"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetURLByCode(ctx context.Context, code string) (*GetURLByCodeRow, error) {
	row := q.db.QueryRow(ctx, getURLByCode, code)
	var i GetURLByCodeRow
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.IsActive,
		&i.ExpiresAt,
	)
	return &i, err
}

const getURLByID = `-- name: GetURLByID :one
SELECT id, code, long_url, long_url_hash, user_id, created_at, expires_at, is_active, is_private, clicks
FROM urls
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetURLByID(ctx context.Context, id int64) (*Url, error) {
	row := q.db.QueryRow(ctx, getURLByID, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.LongUrl,
		&i.LongUrlHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.IsPrivate,
		&i.Clicks,
	)
	return &i, err
}

const getURLsByUser = `-- name: GetURLsByUser :many
SELECT id, code, long_url, long_url_hash, clicks, created_at, expires_at, is_active
FROM urls
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetURLsByUserRow struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	LongUrl     string             `json:"long_url"`
	LongUrlHash []byte             `json:"long_url_hash"`
	Clicks      int64              `json:"clicks"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	IsActive    bool               `json:"is_active"`
}

func (q *Queries) GetURLsByUser(ctx context.Context, userID pgtype.UUID) ([]*GetURLsByUserRow, error) {
	rows, err := q.db.Query(ctx, getURLsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetURLsByUserRow
	for rows.Next() {
		var i GetURLsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.LongUrl,
			&i.LongUrlHash,
			&i.Clicks,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementClicks = `-- name: IncrementClicks :exec
UPDATE urls
SET clicks = clicks + 1
WHERE id = $1
`

func (q *Queries) IncrementClicks(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementClicks, id)
	return err
}
